# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blue Hen Treats
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blue Hen Treats is a local non profit organization that supports local charities through the sale of dehydrated and baked goods.
  These products are prepared and distributed by unpaid volunteers. The products are prepared in the commercial kitchen of Belvedere Fire Co.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://bluehentreats.com/" # the base hostname & protocol for your site
collections:
  - people

# Build settings
markdown: kramdown
future: true
encoding: UTF-8
