# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blue Hen Treats
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  *Blue Hen Treats is a non-profit organization in Delaware. Our volunteers prepare various dehydrated foods for your enjoyment.
  All income, beyond the cost of raw materials and incidentals, is donated to Delaware charities. There are no salaries. Presently, we operate out of the Belvedere Fire Co. commercial kitchen. Our future goal is to prepare our products in our own facility with the help of people with special needs.

baseurl: "/bluehentreats" # the subpath of your site, e.g. /blog
url: "https://veggiedefender.github.io" # the base hostname & protocol for your site
collections:
  - people

# Build settings
markdown: kramdown
future: true
encoding: UTF-8
